import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('fr');

  Locale get currentLocale => _currentLocale;

  bool get isArabic => _currentLocale.languageCode == 'ar';

  void toggleLanguage() {
    if (_currentLocale.languageCode == 'fr') {
      _currentLocale = const Locale('ar');
    } else {
      _currentLocale = const Locale('fr');
    }
    notifyListeners();
  }

  String translate(String key) {
    if (isArabic) {
      return _translationsAr[key] ?? key;
    }
    return _translationsFr[key] ?? key;
  }

  static const Map<String, String> _translationsFr = {
    'app_title': 'Notaire IA',
    'login_title': 'Connexion',
    'email_label': 'Nom ou Numéro',
    'password_label': 'Mot de passe',
    'login_button': 'Se connecter',
    'chat_tab': 'Chat',
    'docs_tab': 'Documents',
    'profile_tab': 'Profil',
    'logout': 'Déconnexion',
    'send_hint': 'Écrivez votre message...',
    'notary_bureau': 'Bureau du Notaire',
    'finalized_act': 'Acte finalisé !',
    'download_pdf': 'Télécharger le PDF',
    'admin_panel': 'Administration',
    'manage_users': 'Gestion des Notaires',
    'search_hint': 'Rechercher un acte...',
    'new_chat': 'Nouvelle Discussion',
    'history_title': 'HISTORIQUE RÉCENT',
    'search_chat_hint': 'Rechercher une discussion...',
    'no_results': 'Aucun résultat',
    'welcome_back': 'Bonjour',
    'start_where': 'Par où commencer ?',
    'generate_act': 'Générer un acte',
    'generate_act_desc': 'Sélectionnez le type d\'acte et scannez les CIN.',
    'view_docs': 'Consulter mes documents',
    'view_docs_desc': 'Accédez aux actes déjà générés et validés.',
    'legal_advice': 'Conseil juridique',
    'legal_advice_desc': 'Posez une question à l\'IA notariale.',
    'see_pdf': 'Voir PDF',
    'my_acts': 'Mes Actes',
    'search_filter': 'Recherche & Filtrage',
    'logout_confirm': 'Voulez-vous vraiment vous déconnecter Maître ?',
    'cancel': 'Annuler',
    'act_type_q': 'Quel type d\'acte souhaitez-vous générer ?',
    'immobilier': 'Vente Immobilière',
    'vehicule': 'Vente de Véhicule',
    'societe': 'Vente de Société (Parts)',
    'mariage': 'Acte de Mariage',
    'testament': 'Acte de Testament',
    'hypotheque': 'Acte d\'Hypothèque',
    'refresh': 'Actualiser',
    'add_template': 'Ajouter un Modèle d\'Acte',
    'add_template_desc': 'Choisissez un fichier .pdf ou .docx pour servir de modèle à l\'IA.',
    'choose_file': 'Choisir un fichier',
    'upload_success': 'Modèle ajouté avec succès !',
    'error_loading': 'Erreur lors du chargement',
    'error_upload': 'Erreur lors de l\'upload',
    'created_on': 'Créé le',
    'no_title': 'Acte sans titre',
    'my_profile': 'Mon Profil',
    'unable_load_profile': 'Impossible de charger le profil',
    'bureau': 'Bureau',
    'birth_date': 'Date de naissance',
    'first_name': 'Prénom',
    'last_name': 'Nom',
    'not_specified': 'Non spécifié(e)',
    'all_acts': 'Tous les actes',
    'search_query_hint': 'Entrez un NNI (10 chiffres) ou un nom...',
    'search_start': 'Commencez votre recherche',
    'search_start_desc': 'Entrez un NNI complet ou un nom pour voir les actes.',
    'nni_incomplete': 'NNI incomplet',
    'nni_incomplete_desc': 'Veuillez saisir les 10 chiffres du NNI.',
    'search_short': 'Recherche trop courte',
    'search_short_desc': 'Veuillez saisir au moins 3 caractères.',
    'no_result_found': 'Aucun résultat trouvé',
    'no_result_found_desc': 'Aucun acte ne correspond à votre recherche.',
    'notarial_act': 'Acte Notarié',
    'no_notary_found': 'Aucun notaire trouvé.',
    'user_deactivated': 'Utilisateur désactivé.',
    'confirm_deactivation': 'Confirmer la désactivation',
    'confirm_deactivation_desc': 'Voulez-vous vraiment désactiver ce notaire ?',
    'deactivate': 'Désactiver',
    'error_fetching_users': 'Erreur lors de la récupération des utilisateurs',
    'edit_notary': 'Modifier le Notaire',
    'add_notary': 'Ajouter un Notaire',
    'email_pass_required': 'Email et mot de passe sont obligatoires.',
    'nni_10_digits': 'Le NNI doit comporter exactement 10 chiffres.',
    'notary_updated': 'Notaire mis à jour.',
    'notary_created': 'Notaire créé avec succès.',
    'fail': 'Échec',
    'nni_label': 'NNI (Numéro National d\'Identité)',
    'nni_hint': '10 chiffres requis',
    'phone_label': 'Numéro de Téléphone',
    'phone_hint': '8 chiffres requis',
    'birth_date_hint': 'ex: 01/01/1980',
    'bureau_label': 'Numéro du Bureau',
    'role_label': 'Rôle de l\'utilisateur',
    'admin': 'Administrateur',
    'clerk': 'Notaire / Clerc',
    'save': 'Enregistrer',
    'pass_edit_hint': 'laisser vide pour ne pas changer',
    'register_title': 'Inscription Notaire',
    'new_account': 'Nouveau Compte',
    'fill_required': 'Veuillez remplir tous les champs obligatoires.',
    'register_success': 'Inscription réussie ! Vous pouvez maintenant vous connecter.',
    'register_fail': 'Échec de l\'inscription. L\'email est peut-être déjà utilisé.',
    'register_button': 'S\'inscrire',
    'already_account': 'Déjà un compte ? Se connecter',
    'seal_q': 'Sceller l\'acte ?',
    'seal_desc': 'Une fois le cachet du notaire appliqué, l\'acte sera verrouillé et ne pourra plus être modifié. Voulez-vous continuer ?',
    'seal_button': 'Appliquer le cachet',
    'seal_success': 'Acte scellé avec succès ! Le document est désormais verrouillé.',
    'seal_error': 'Erreur lors du scellement',
    'sealed': 'SCELLÉ',
    'complete': 'Compléter',
    'complete_success': 'Acte finalisé avec succès !',
    'complete_update': 'Acte mis à jour.',
    'fields_left': 'champ(s) restant(s).',
    'pdf_loading': 'Chargement du PDF…',
    'pdf_fetch': 'Document en cours de récupération',
    'pdf_error_fetch': 'Impossible de charger le PDF',
    'retry': 'Réessayer',
    'zoom_in': 'Zoom avant',
    'zoom_out': 'Zoom arrière',
    'open_link': 'Ouvrir le lien',
    'timeout': 'Délai d\'attente dépassé',
    'complete_act': 'Compléter l\'acte',
    'complete_mariage': 'Compléter l\'acte de mariage',
    'complete_immobilier': 'Compléter l\'acte de vente immobilière',
    'complete_vehicule': 'Compléter l\'acte de vente de véhicule',
    'complete_societe': 'Compléter l\'acte de cession de parts',
    'complete_testament': 'Compléter l\'acte de testament',
    'complete_hypotheque': 'Compléter l\'acte d\'hypothèque',
    'missing_info_desc': 'information(s) manquante(s). Remplissez ces champs pour générer l\'acte final sans points vides.',
    'later': 'Plus tard',
    'finalize_button': 'Finaliser l\'acte',
    'seller': 'Vendeur',
    'buyer': 'Acheteur',
    'husband': 'Monsieur',
    'wife': 'Madame',
    'testator': 'Testateur',
    'beneficiary': 'Bénéficiaire',
    'debtor': 'Débiteur',
    'creditor': 'Créancier',
    'id_sent_p1': '📷 Carte d\'identité {label} envoyée.',

    'id_received_p1': 'Carte d\'identité du {label} reçue ✓\n\nMaintenant, veuillez envoyer la carte d\'identité de {label2}.',
    'id_sent_p2': '📷 Carte d\'identité {label} envoyée.',
    'send_carte_grise_recto': 'Carte d\'identité de l\'Acheteur reçue ✓\n\nMaintenant, veuillez envoyer la Carte Grise (RECTO / FACE).',
    'send_permis_occuper': 'Carte d\'identité du {label} reçue ✓\n\nMaintenant, veuillez envoyer la photo du PERMIS D\'OCCUPER pour que je puisse extraire les données du bien.',
    'analyzing_ids': '⚙️ Analyse des pièces d\'identité en cours… Génération de l\'acte de type {type}.',
    'cg_recto_sent': '📷 Carte Grise (Recto) envoyée.',
    'send_cg_verso': 'La face de la carte grise a été reçue. ✓\n\nVeuillez maintenant envoyer le VERSO (DOS) pour que je puisse extraire les données techniques.',
    'cg_verso_sent': '📷 Carte Grise (Verso) envoyée.',
    'all_pieces_received': 'Excellent Maître. J\'ai toutes les pièces (IDs + Carte Grise). ✓\n\n⚙️ Analyse et extraction des données techniques en cours...',
    'permis_sent': '📷 Permis d\'Occuper envoyé.',
    'permis_received': 'Excellent Maître. J\'ai bien reçu le Permis d\'Occuper. ✓\n\n⚙️ Analyse et extraction des données du terrain en cours...',
    'act_generated_success': '✅ Brouillon d\'acte de {type} généré !\n\n• {label1} : {name1}\n• {label2} : {name2}',
    "ask_price_vehicule": "Excellent Maître. J'ai bien extrait toutes les informations techniques du véhicule. ✓\n\nMaintenant, quel est le prix de vente (en MRU) pour finaliser l'acte ?",
    "hypotheque_step1": "Pièces d'identité et Permis d'Occuper analysés avec succès. ✓\n\nPour finaliser l'acte d'hypothèque, j'ai besoin de quelques précisions :\n\n1. Quel est le montant de la dette ?",
    "ask_price_immobilier": "Excellent Maître. J'ai bien extrait toutes les informations du terrain à partir du permis d'occuper. ✓\n\nMaintenant, quel est le prix de vente du terrain (en MRU) pour finaliser l'acte ?",
    "price_saved_immobilier": "✅ Prix enregistré : {price} MRU\n\nL'acte de vente immobilière a été finalisé avec succès Maître. Vous pouvez consulter le document final ci-dessous.",
    "price_saved": "✅ Prix enregistré : {price} MRU\n\nL'acte de vente de véhicule a été finalisé avec succès Maître. Vous pouvez consulter le document final ci-dessous.",
    'act_updated_missing': '📄 Acte mis à jour. Certains champs manquent encore.',
    'hypotheque_step2': 'Très bien. Quelle est la durée de remboursement prévue ?',
    'hypotheque_step3': 'Entendu. Quelles sont les conditions d\'exécution en cas de non-paiement ?',
    "hypotheque_final": "✅ Acte d'hypothèque finalisé !\n\nToutes les informations ont été enregistrées. Vous pouvez consulter l'acte final ci-dessous.",
    'field_saved': '✓ Enregistré.\n\n{next}',
    'form_cancelled': 'Formulaire annulé. Vous pouvez télécharger le brouillon ou compléter plus tard.',
    'completion_needed': '⚠️ L\'acte est incomplet. {count} information(s) manquante(s). Un formulaire va s\'ouvrir pour les compléter.',
    'cg_extracted_price_needed': "✅ Données de la carte grise extraites avec succès !\n\nIl ne manque plus que le prix de vente pour finaliser l'acte. Un formulaire va s'ouvrir.",
    'start_chat_title': 'Démarrage : {title}',
    'start_chat_id_request': 'Très bien Maître. Veuillez envoyer la carte d\'identité {label}.',
    'generation_error': '❌ Erreur lors de la génération : {error}',
    'draft_generated_log': 'Brouillon généré — {p1}: {name1}, {p2}: {name2}',
  };


  static const Map<String, String> _translationsAr = {
    'app_title': 'الموثق الذكي',
    'login_title': 'تسجيل الدخول',
    'email_label': 'الاسم أو الرقم',
    'password_label': 'كلمة المرور',
    'login_button': 'دخول',
    'chat_tab': 'المحادثة',
    'docs_tab': 'المستندات',
    'profile_tab': 'الملف الشخصي',
    'logout': 'تسجيل الخروج',
    'send_hint': 'اكتب رسالتك...',
    'notary_bureau': 'مكتب الموثق',
    'finalized_act': 'تم الانتهاء من العقد!',
    'download_pdf': 'تحميل ملف PDF',
    'admin_panel': 'لوحة الإدارة',
    'manage_users': 'إدارة الموثقين',
    'search_hint': 'البحث عن عقد...',
    'new_chat': 'محادثة جديدة',
    'history_title': 'السجل الأخير',
    'search_chat_hint': 'البحث في المحادثات...',
    'no_results': 'لا توجد نتائج',
    'welcome_back': 'مرحباً',
    'start_where': 'من أين نبدأ؟',
    'generate_act': 'إنشاء عقد',
    'generate_act_desc': 'اختر نوع العقد وقم بمسح بطاقات الهوية.',
    'view_docs': 'تصفح مستنداتي',
    'view_docs_desc': 'الوصول إلى العقود التي تم إنشاؤها والموافقة عليها.',
    'legal_advice': 'استشارة قانونية',
    'legal_advice_desc': 'اطرح سؤالاً على الموثق الذكي.',
    'see_pdf': 'عرض PDF',
    'my_acts': 'عقودي',
    'search_filter': 'البحث والتصفية',
    'logout_confirm': 'هل تريد حقًا تسجيل الخروج يا أستاذ؟',
    'cancel': 'إلغاء',
    'act_type_q': 'ما هو نوع العقد الذي تريد إنشاءه؟',
    'immobilier': 'بيع عقاري',
    'vehicule': 'بيع مركبة',
    'societe': 'بيع شركة (حصص)',
    'mariage': 'عقد زواج',
    'testament': 'عقد وصية',
    'hypotheque': 'عقد رهن',
    'refresh': 'تحديث',
    'add_template': 'إضافة نموذج عقد',
    'add_template_desc': 'اختر ملف .pdf أو .docx ليكون نموذجاً للذكاء الاصطناعي.',
    'choose_file': 'اختيار ملف',
    'upload_success': 'تمت إضافة النموذج بنجاح!',
    'error_loading': 'خطأ أثناء التحميل',
    'error_upload': 'خطأ أثناء الرفع',
    'created_on': 'أنشئ في',
    'no_title': 'عقد بدون عنوان',
    'my_profile': 'ملفي الشخصي',
    'unable_load_profile': 'تعذر تحميل الملف الشخصي',
    'bureau': 'المكتب',
    'birth_date': 'تاريخ الميلاد',
    'first_name': 'الاسم الأول',
    'last_name': 'اللقب',
    'not_specified': 'غير محدد',
    'all_acts': 'جميع العقود',
    'search_query_hint': 'أدخل رقم الهوية (10 أرقام) أو اسماً...',
    'search_start': 'ابدأ البحث',
    'search_start_desc': 'أدخل رقم هوية كاملاً أو اسماً لعرض العقود.',
    'nni_incomplete': 'رقم الهوية غير مكتمل',
    'nni_incomplete_desc': 'يرجى إدخال 10 أرقام لرقم الهوية.',
    'search_short': 'البحث قصير جداً',
    'search_short_desc': 'يرجى إدخال 3 أحرف على الأقل.',
    'no_result_found': 'لم يتم العثور على نتائج',
    'no_result_found_desc': 'لا يوجد عقد يطابق بحثك.',
    'notarial_act': 'عقد توثيق',
    'no_notary_found': 'لم يتم العثور على أي موثق.',
    'user_deactivated': 'تم إلغاء تفعيل المستخدم.',
    'confirm_deactivation': 'تأكيد إلغاء التفعيل',
    'confirm_deactivation_desc': 'هل تريد حقاً إلغاء تفعيل هذا الموثق؟',
    'deactivate': 'إلغاء التفعيل',
    'error_fetching_users': 'خطأ أثناء جلب المستخدمين',
    'edit_notary': 'تعديل الموثق',
    'add_notary': 'إضافة موثق',
    'email_pass_required': 'البريد الإلكتروني وكلمة المرور مطلوبان.',
    'nni_10_digits': 'يجب أن يتكون رقم الهوية من 10 أرقام بالضبط.',
    'notary_updated': 'تم تحديث الموثق.',
    'notary_created': 'تم إنشاء الموثق بنجاح.',
    'fail': 'فشل',
    'nni_label': 'رقم الهوية (NNI)',
    'nni_hint': 'مطلوب 10 أرقام',
    'phone_label': 'رقم الهاتف',
    'phone_hint': 'مطلوب 8 أرقام',
    'birth_date_hint': 'مثال: 01/01/1980',
    'bureau_label': 'رقم المكتب',
    'role_label': 'دور المستخدم',
    'admin': 'مشرف',
    'clerk': 'موثق / كاتب',
    'save': 'حفظ',
    'pass_edit_hint': 'اتركه فارغاً لعدم التغيير',
    'register_title': 'تسجيل موثق',
    'new_account': 'حساب جديد',
    'fill_required': 'يرجى ملء جميع الحقول المطلوبة.',
    'register_success': 'نجح التسجيل! يمكنك الآن تسجيل الدخول.',
    'register_fail': 'فشل التسجيل. البريد الإلكتروني قد يكون مستخدماً بالفعل.',
    'register_button': 'تسجيل',
    'already_account': 'لديك حساب بالفعل؟ تسجيل الدخول',
    'seal_q': 'هل تريد ختم العقد؟',
    'seal_desc': 'بمجرد وضع ختم الموثق، سيتم قفل العقد ولن يمكن تعديله. هل تريد الاستمرار؟',
    'seal_button': 'وضع الختم',
    'seal_success': 'تم ختم العقد بنجاح! المستند مقفل الآن.',
    'seal_error': 'خطأ أثناء الختم',
    'sealed': 'مختوم',
    'complete': 'إكمال',
    'complete_success': 'تم إنهاء العقد بنجاح!',
    'complete_update': 'تم تحديث العقد.',
    'fields_left': 'حقل (حقول) متبقية.',
    'pdf_loading': 'جاري تحميل PDF…',
    'pdf_fetch': 'جاري جلب المستند',
    'pdf_error_fetch': 'تعذر تحميل PDF',
    'retry': 'إعادة المحاولة',
    'zoom_in': 'تكبير',
    'zoom_out': 'تصغير',
    'open_link': 'فتح الرابط',
    'timeout': 'انتهت مهلة الانتظار',
    'complete_act': 'إكمال العقد',
    'complete_mariage': 'إكمال عقد الزواج',
    'complete_immobilier': 'إكمال عقد البيع العقاري',
    'complete_vehicule': 'إكمال عقد بيع المركبة',
    'complete_societe': 'إكمال عقد التنازل عن الحصص',
    'complete_testament': 'إكمال عقد الوصية',
    'complete_hypotheque': 'إكمال عقد الرهن',
    'missing_info_desc': 'معلومات مفقودة. املأ هذه الحقول لإنشاء العقد النهائي بدون ثغرات.',
    'later': 'لاحقاً',
    'finalize_button': 'إنهاء العقد',
    'seller': 'البائع',
    'buyer': 'المشتري',
    'husband': 'الزوج / السيد',
    'wife': 'الزوجة / السيدة',
    'testator': 'الموصي',
    'beneficiary': 'المستفيد',
    'debtor': 'المدين',
    'creditor': 'الدائن',
    'id_sent_p1': '📷 تم إرسال بطاقة تعريف {label}.',

    'id_received_p1': 'تم استلام بطاقة تعريف {label} ✓\n\nالآن، يرجى إرسال بطاقة تعريف {label2}.',
    'id_sent_p2': '📷 تم إرسال بطاقة تعريف {label}.',
    'send_carte_grise_recto': 'تم استلام بطاقة تعريف المشتري ✓\n\nالآن، يرجى إرسال البطاقة الرمادية (الوجه الأمامي).',
    'send_permis_occuper': 'تم استلام بطاقة تعريف {label} ✓\n\nالآن، يرجى إرسال صورة إذن الإشغال لاستخراج بيانات العقار.',
    'analyzing_ids': '⚙️ جاري تحليل بطاقات الهوية... إنشاء عقد من نوع {type}.',
    'cg_recto_sent': '📷 تم إرسال البطاقة الرمادية (الوجه).',
    'send_cg_verso': 'تم استلام وجه البطاقة الرمادية. ✓\n\nيرجى الآن إرسال الظهر (الوجه الخلفي) لاستخراج البيانات التقنية.',
    'cg_verso_sent': '📷 تم إرسال البطاقة الرمادية (الظهر).',
    'all_pieces_received': 'ممتاز يا أستاذ. لدي جميع الوثائق (البطاقات + البطاقة الرمادية). ✓\n\n⚙️ جاري تحليل واستخراج البيانات التقنية...',
    'permis_sent': '📷 تم إرسال إذن الإشغال.',
    'permis_received': 'ممتاز يا أستاذ. لقد استلمت إذن الإشغال. ✓\n\n⚙️ جاري تحليل واستخراج بيانات الأرض...',
    'act_generated_success': '✅ تم إنشاء مسودة {type} بنجاح!\n\n• {label1} : {name1}\n• {label2} : {name2}',
    'ask_price_vehicule': 'ممتاز يا أستاذ. لقد استخرجت جميع المعلومات التقنية للمركبة. ✓\n\nالآن، ما هو سعر البيع (بالأوقية) لإنهاء العقد؟',
    'hypotheque_step1': 'تم تحليل بطاقات الهوية وإذن الإشغال بنجاح. ✓\n\nلإنهاء عقد الرهن، أحتاج إلى بعض التوضيحات:\n\n1. ما هو مبلغ الدين؟',
    'price_saved': '✅ تم تسجيل السعر: {price} أوقية\n\nتم إنهاء عقد بيع المركبة بنجاح يا أستاذ. يمكنك الاطلاع على المستند النهائي أدناه.',
    'act_updated_missing': '📄 تم تحديث العقد. لا تزال بعض الحقول مفقودة.',
    'hypotheque_step2': 'جيد جداً. ما هي مدة السداد المتوقعة؟',
    'hypotheque_step3': 'مفهوم. ما هي شروط التنفيذ في حالة عدم الدفع؟',
    'hypotheque_final': '✅ تم إنهاء عقد الرهن بنجاح!\n\nتم تسجيل جميع المعلومات. يمكنك الاطلاع على العقد النهائي أدناه.',
    'field_saved': '✓ تم التسجيل.\n\n{next}',
    'form_cancelled': 'تم إلغاء النموذج. يمكنك تحميل المسودة أو الإكمال لاحقاً.',
    'completion_needed': '⚠️ العقد غير مكتمل. هناك {count} معلومة مفقودة. سيفتح نموذج لإكمالها.',
    'cg_extracted_price_needed': '✅ تم استخراج بيانات البطاقة الرمادية بنجاح!\n\nلم يتبق سوى سعر البيع لإنهاء العقد. سيفتح نموذج.',
    'start_chat_title': 'بدء : {title}',
    'start_chat_id_request': 'ممتاز يا أستاذ. يرجى إرسال بطاقة تعريف {label}.',
    'generation_error': '❌ خطأ أثناء الإنشاء : {error}',
    'draft_generated_log': 'تم إنشاء المسودة — {p1}: {name1}، {p2}: {name2}',
    "ask_price_immobilier": "ممتاز يا أستاذ. لقد قمت باستخراج جميع معلومات العقار من إذن الإشغال بنجاح. ✓\n\nالآن، ما هو ثمن بيع الأرض (بالأوقية) لإكمال العقد؟",
    "price_saved_immobilier": "✅ تم تسجيل الثمن: {price} أوقية\n\nتم إكمال عقد البيع العقاري بنجاح يا أستاذ. يمكنك الاطلاع على المستند النهائي أدناه.",
  };

}
