"""Add nni column to user

Revision ID: 10bdf5fd7940
Revises: cb1f46789d54
Create Date: 2026-04-13 12:47:17.125853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bdf5fd7940'
down_revision: Union[str, Sequence[str], None] = 'cb1f46789d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nni', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_nni'), 'users', ['nni'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nni'), table_name='users')
    op.drop_column('users', 'nni')
    # ### end Alembic commands ###
