"""Add bureau to user

Revision ID: 2e0cf97fd6e5
Revises: c89581884b0c
Create Date: 2026-04-02 14:30:44.970652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0cf97fd6e5'
down_revision: Union[str, Sequence[str], None] = 'c89581884b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bureau', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bureau')
    # ### end Alembic commands ###
