"""Add user roles and activity status

Revision ID: c89581884b0c
Revises: cd76eb6406f1
Create Date: 2026-03-31 12:40:14.797714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89581884b0c'
down_revision: Union[str, Sequence[str], None] = 'cd76eb6406f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type manually for PostgreSQL
    user_role_enum = sa.Enum('ADMIN', 'NOTAIRE', 'CLERC', name='userrole')
    user_role_enum.create(op.get_bind())

    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'NOTAIRE', 'CLERC', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')

    # Drop the Enum type manually for PostgreSQL
    user_role_enum = sa.Enum('ADMIN', 'NOTAIRE', 'CLERC', name='userrole')
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
